### ISSUE TITLE
how to create my own dataset?

### ISSUE THREAD

**Issue by adminmyw** [ahmedfgad/NumPyCNN#12]
your code is wonderful!
but I have one question: how to create my own dataset use code. And how to label or training it?
thank you !

**Comment by ahmedfgad** [comment]
Thank you!

The dataset is simply a NumPy array saved into a `.npy` file. 

You can simply use a loop that reads some images, append each image into a NumPy array, and save the final array into a `.npy` file. This would help: https://gist.github.com/anilsathyan7/ffb35601483ac46bd72790fde55f5c04
