### ISSUE TITLE
size of pool_out

### ISSUE THREAD

**Issue by jovahe** [ahmedfgad/NumPyCNN#2]
The size of input image is (512,512), and  the size of conv1_out is (510,510), the size of pool_out should be (255,255). However the size of pool_out is (254,254). So I suggest that the codes in pooling() function should be changed as following:
pool_out = np.zeros((np.uint16((feature_map.shape[0]-size)/stride+1),
                        np.uint16((feature_map.shape[1]-size)/stride+1),
                        feature_map.shape[-1]))

**Comment by beiyan1911** [comment]
上面正解

**Comment by ahmedfgad** [comment]
The issue is closed due to being solved.
