### ISSUE TITLE
A code error in relu function

### ISSUE THREAD

**Issue by MapleSpirit** [ahmedfgad/NumPyCNN#4]
The current relu function actually does no work for the feature_map.
The code `relu_out[r, c, map_num] = numpy.max(feature_map[r, c, map_num], 0)`  should be written as 
`relu_out[r, c, map_num] = numpy.max([feature_map[r, c, map_num], 0])`
And thanks for the code you shared!

**Comment by ahmedfgad** [comment]
Thanks. The bug is fixed according to your comment.
